### ISSUE TITLE
Not Support Unix(macOS): ln: /usr/bin/note: Operation not permitted

### ISSUE THREAD

**Issue by JimmyLv** [urnote/urnote#2]
```bash
sudo ./install.sh
Password:
Sorry, try again.
Password:
readlink: illegal option -- f
usage: readlink [-n] [file ...]
ln: /usr/bin/note: Operation not permitted
```

**Comment by JimmyLv** [comment]
btw: 用得是什么记忆算法呀？非常感兴趣！非常契合我用纯文本管理笔记的愿景！

**Comment by jefffffrey** [comment]
你好，这个问题是由于Mac上不支持`readlink -f`的用法，你可以试一下直接使用ln创建链接：`sudo ln -s ./note /usr/bin/note`。
另外由于我现在没有Mac的环境因此无法修改和测试这个sh文件让它支持Mac，你能帮我修改一下吗? [参考链接](https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself)。
这里用到的算法类似于[SuperMemo 2: Algorithm](https://www.supermemo.com/english/ol/sm2.htm)大概就是设定一个初始间隔，然后根据（复习评分，提前复习|按时复习|延后复习）调整下次复习间隔。如有需要可以直接阅读源代码[review algorithm](https://github.com/jefffffrey/smart-note/blob/master/note/utils/review_algorithm.py)。

**Comment by toaco** [comment]
已经支持Mac了
